# Base image
FROM python:3.11-slim

# Copy files from local parent directory to container's working directory
ARG CONTAINER_WORKDIR_NAME
WORKDIR /${CONTAINER_WORKDIR_NAME}
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
ARG WEBSERVER_REQUIREMENTS_NAME
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu -r ${WEBSERVER_REQUIREMENTS_NAME} && \
    rm -rf /root/.cache/pip

# Run the FastAPI server using uvicorn
CMD ["uvicorn", "webserver:fastApiApp", "--host", "0.0.0.0", "--port", "8000"]